In [9]:
import numpy as np 
a = np.array([[1,2,3,4,5,6,7,8,9,10],[1,1,1,1,1,1,1,1,1,1]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  1  1  1  1  1  1  1  1  1]]


In [22]:
print(a.mean(axis = 1)) # Среднее
print(a.mean(axis = 0)) # Среднее
print()
print(a.std(axis = 1)) # Стандартное отклонение
print(a.var(axis = 1,ddof = 0 )) # Дисперсия
print(np.median(a, axis = 1))

[5.5 1. ]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]

[2.87228132 0.        ]
[8.25 0.  ]
[5.5 1. ]
